### ISSUE TITLE
README.md Datei befüllen

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#11]
kurze Beschreibung des Projekts und des Repositories

**Comment by jessvasseur** [comment]
* Kurzzusammenfassung Projekt
* Überblick Wiki
* visuelle Darstellung Projekt
* Verlinkung auf Wiki für Details

**Comment by Regfis** [comment]
Ich würde mich gerne darum kümmern :-)
