### ISSUE TITLE
Anzahl der Patienten mit Brustkrebs?

### ISSUE THREAD

**Issue by Regfis** [Fuenfgeld/DMA2023TeamA#12]

**Comment by Regfis** [comment]
Kann man davon ausgehen, dass alle Patienten in der Patient-Tabelle des Brustkrebs-Datensatzes auch wirklich Brustkrebs haben?

**Comment by Fuenfgeld** [comment]
Müsst ihr überprüfen.

**Comment by jessvasseur** [comment]
von den 1019 Patient:innen im Datensatz ist für 884 Patient:innen keine Diagnose in der Tabelle conditions.csv verfügbar; von den verbleibenden 135 Patient:innen haben 11 den SNOMED Code 254837009 = Malignant neoplasm of breast (disorder), ansonsten alles Diagnosen mit kardiovaskulären Ereignissen. Auch nur für diese 11 Patient:innen ist Brustkrebs als Grund für einen Fall oder eine Prozedur angegeben (in der Tabelle encounters.csv bzw. procedures.csv).

Daher stellt sich für uns die Frage, ob tatsächlich nur diese 11 Patient:innen Brustkrebs haben - dann macht eine Subgruppenanalyse weniger Sinn? oder haben alle im Datensatz enthaltenen Patient:innen Brustkrebs, aber die Diagnose an sich ist nicht aus dem Datensatz ersichtlich?
