### ISSUE TITLE
SQL Statements als Code ablegen

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#16]
SQL Statements für Generierung der Datenbanktabellen (z.B. https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22patients%22) nicht in Wiki sondern als Code in Repository ablegen
(siehe https://github.com/Fuenfgeld/DMA2023TeamA/issues/7)

**Comment by THGthub** [comment]
In der Wiki Permalinks auf die Codeblöcke der SQL-CREATE TABLE-Statements der jeweiligen Tabellen im Skript [Setup_and_fill_Database.ipynb](https://github.com/Fuenfgeld/DMA2023TeamA/blob/298f5d5bdd9259be2d34f7fda05550f82b31f15a/Code/Setup_and_fill_Database.ipynb) gesetzt.

**Comment by THGthub** [comment]
Durch die Permalinks behoben.
