### ISSUE TITLE
Spaltendokumentation Datenbanktabellen ergänzen

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#17]
genauere Beschreibung der Spalten der Datenbanktabellen in Dokumentation (z.B. https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22patients%22) ergänzen - Datentypen, Informationen, Standardterminologien etc.
(siehe https://github.com/Fuenfgeld/DMA2023TeamA/issues/7)

**Comment by THGthub** [comment]
Für die dokumentierten Tabellen [patients](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22patients%22), [payers](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22Payers%22), [encounters](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22Encounters%22), [procedures](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22Procedures%22), [conditions](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22Conditions%22), [payer_transitions](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22Payer-Transitions%22) im Wiki eine Spalte "Beschreibung" eingefügt und dort allgemeine Informationen über die einzelnen Spalten der Tabellen in der Datenbank hinterlegt.

**Comment by THGthub** [comment]
Für alle Definitionen im Wiki wurden Tabellen mit Informationen über den Spalten generiert.
