### ISSUE TITLE
Forschungsfrage definieren

### ISSUE THREAD

**Issue by THGthub** [Fuenfgeld/DMA2023TeamA#2]
Definition der Forschungsfrage mit:

- Angabe des zugrundeliegenden synthetischen Datensatzes
- Forschungsgegenstand (Krankheitsbild)
- Zielsetzung

**Comment by jessvasseur** [comment]
https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Forschungsfrage

**Comment by jessvasseur** [comment]
> Finanzielle Einbußen für Patienten, Versicherungen und die Allgemeinheit durch eine Brustkrebserkrankung.

wäre es vielleicht sinnvoller sich auf die Patienten zu beschränken? "Allgemeinheit" können wir sowieso nicht ablesen aus dem Datensatz. Wenn wir die Versicherungen hinzunehmen, wird die Analyse komplizierter.

**Comment by Regfis** [comment]
Da hast du recht. Dann entferne ich die "Allgemeinheit"
