### ISSUE TITLE
Relevante Daten identifizieren

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#22]
Dokumentation der für die Forschungsfrage benötigten Tabellenspalten

**Comment by jessvasseur** [comment]
[Tabelle patients](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22patients%22)
* Id
* demografische Daten (Gender, BirthDate/Age, Ethnicity)
* Healthcare_Expenses, Healthcare_Coverage

[Tabelle procedures](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22procedures%22)
* Patient
* Encounter
* Code
* Base_Cost
* Reason_Code

[Tabelle medications](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22medications%22)
* Patient
* Payer
* Encounter
* Code
* Base_Cost
* Payer_Coverage
* Dispenses
* TotalCost
* ReasonCode

[Tabelle encounters](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22encounters%22)
* Id
* Patient
* Payer
* Base_Encounter_Cost
* Total_Claim_Cost
* Payer_Coverage
* ReasonCode

[Tabelle conditions](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22conditions%22)
* Patient
* Encounter
* Code

[Tabelle payers](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22payers%22)
* Id
* Name

[Tabelle payer_transitions](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22payer_transitions%22)
* keine

**Comment by jessvasseur** [comment]
für eine einfachere Analyse könnte man vermutlich auf medications und procedures verzichten. die damit verbundenen Kosten sind auch in encounters enthalten (Spalte Total_Claim_Cost), oder?

**Comment by Regfis** [comment]
Ich denke schon, dass es interessant wäre, was die Medikamente und Untersuchungen kosten.
