### ISSUE TITLE
Vorbereitung der Datenbank für die EDA 

### ISSUE THREAD

**Issue by Regfis** [Fuenfgeld/DMA2023TeamA#26]
Löschen der nicht benötigten Spalten aus den ausgewählten Tabellen. 
Suchen nach NULL-Werten, Suche nach unvollständigen Datensätzen.
Überlegung, ob und wie diese "Lücken" gefüllt werden sollen.

**Comment by jessvasseur** [comment]
Läuft das über die Erstellung eines "Views" in der Data Warehouse Datenbank?
