### ISSUE TITLE
Rahmen für die Präsentation überlegen

### ISSUE THREAD

**Issue by Regfis** [Fuenfgeld/DMA2023TeamA#29]
Überlegungen, wie die Präsentation aufgebaut werden soll. Und wer welchen Teil übernehmen möchte.
Überlegung zu Layout, Präsentationsform etc.

**Comment by THGthub** [comment]
https://docs.google.com/presentation/d/1l_HuSCHGyF_vD3kwdv7pv6GTNtiDJdFeDzQK877iPjk/edit#slide=id.g18959c1292e_0_309

Sammelstelle für Präsentationsideen.

**Comment by jessvasseur** [comment]
Entscheidung gegen Präsentation, stattdessen Entwicklung eines Szenarios in separatem [Google Doc](https://docs.google.com/document/d/1bwCx6BBPRRLH0Kg6mwpSJFu90fQPaz2I310_A71M-9I/edit?usp=share_link) - siehe https://github.com/Fuenfgeld/DMA2023TeamA/issues/51
