### ISSUE TITLE
Versionen der verwendeten Python-Libraries dokumentieren

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#32]
Dokumentation der verwendeten Versionen von Python und Bibliotheken zwecks Reproduzierbarkeit
* Anpassung innerhalb des Codes
* Dokumentation im Wiki (Systemumgebung) (projektspezifisch)

**Comment by THGthub** [comment]
In der Wiki-Page zur [Systemumgebung](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Systemumgebung) wurden die verwendeten Versionen der Python-Bibliotheken (und von Python selbst) bereits dokumentiert.

**Comment by THGthub** [comment]
Im ETL-Skript angepasst, dass die verwendeten Versionen der Python-Bibliotheken, und von Python selbst, ausgegeben werden. Codeänderung mittels #42 in einem Pull-Request dokumentiert.

**Comment by THGthub** [comment]
Im setup_and_fill_Database-Skript angepasst, dass die verwendeten Versionen der Python-Bibliotheken, und von Python selbst, ausgegeben werden. Codeänderung mittels https://github.com/Fuenfgeld/DMA2023TeamA/pull/43 in einem Pull-Request dokumentiert.
