### ISSUE TITLE
Dokumentation zum ETL Prozess ergänzen

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#34]
Beschreibung des (bisherigen) ETL-Prozesses auf eigener Wiki-Page

https://github.com/Fuenfgeld/DMA2023TeamA/wiki/ETL-Prozess

**Comment by THGthub** [comment]
ETL-Prozess dokumentiert: https://github.com/Fuenfgeld/DMA2023TeamA/wiki/ETL-Prozess. Es fehlt noch die Beschreibung der Abhängigkeiten der Mappingtabellen. Die Beschreibung hat allerdings noch keinen Sinn, das sich die Mappingtabellen ggf. noch ändern können. Auch der Link für die Datenschutzfolgeabschätzung fehlt noch, sowie eine Beschreibung der Anonymisierung, da zum Zeitpunkt der Wiki-Page-Erstellung die Informationen noch nicht vorhanden waren.

**Comment by THGthub** [comment]
Link auf die [Datenschutz-Folgenabschätzung](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenschutz-Folgenabsch%C3%A4tzung) erstellt, Link auf die Wiki-Page mit dem [Datenbankschema des Datawarehouse](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankschema-Datawarehouse) ergänzt.

**Comment by THGthub** [comment]
Als Teil des ETL-Prozesses kann die Anonymisierung und Pseudonymisierung gesehen werden. Diese wurde in der Issue #50 programmiert und eine [Wiki-Seite](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Anonymisierung-und--Pseudonymisierung) wurde erstellt. Der Pull-Request zu den Änderungen am ETL-Skript ist #65. In der ETL-Wiki-Seite muss nur noch ein Verweis auf die Anonymisierung und Pseudonymisierung erfolgen, dann kann diese Issue geschlossen werden.

**Comment by THGthub** [comment]
Die Doku wurde um die Beschreibung der Anonymisierung und Pseudonymisierung ergänzt. Die vollstände, fertige ETL-Prozessbeschreibung ist hier gespeichert [ETL-Prozess](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/ETL-Prozess)
