### ISSUE TITLE
Projekttitel festlegen

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#35]
Brainstorming und Bestimmung eines kurzen Projekttitels

Verwendung in
* [Wiki-Home](https://github.com/Fuenfgeld/DMA2023TeamA/wiki)
* [Datenmanagementplan](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenmanagementplan)
* [README.md](https://github.com/Fuenfgeld/DMA2023TeamA/blob/main/README.md)

**Comment by Regfis** [comment]
Wie wäre "Krebs als Schuldenfalle (KraS)

**Comment by jessvasseur** [comment]
KraS finde ich gut https://cancercommons.org/latest-insights/the-trouble-with-kras/ :)
