### ISSUE TITLE
Datenquellen definieren

### ISSUE THREAD

**Issue by Regfis** [Fuenfgeld/DMA2023TeamA#4]
Definition der relevanten Tabellen aus den gegebenen Datenquellen.

**Comment by jessvasseur** [comment]
https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary

**Comment by jessvasseur** [comment]
für die Forschungsfrage sind die folgenden Tabellen relevant: patients, encounters, conditions, payers, payers_transitions, procedures
