### ISSUE TITLE
Datenschutzfolgenabschätzung erstellen

### ISSUE THREAD

**Issue by THGthub** [Fuenfgeld/DMA2023TeamA#47]
Links sammeln für eine Vorlage der Datenschutzfolgeabschätzung bzw. Diskussion über den Inhalt der DSGVO.

**Comment by jessvasseur** [comment]
meine gesammelten Werke zur DSFA :) 

[Infos BFDI](https://www.bfdi.bund.de/DE/Fachthemen/Inhalte/Technik/Datenschutz-Folgenabschaetzungen.html)
[Muster BFDI](https://www.bfdi.bund.de/SharedDocs/Downloads/DE/Muster/Muster_Hinweise_DSFA.pdf)
[Gesundheitsdatenschutz mit Vorlagen](https://gesundheitsdatenschutz.org/html/dsfa-beispiel.php)
[MII Datenschutzkonzept mit DSFA](https://www.medizininformatik-initiative.de/sites/default/files/2022-03/MII-Datenschutzkonzept_v1.0.pdf)
[Allgemeine Infos Bitkom](https://www.bitkom.org/Bitkom/Publikationen/Risk-Assessment-Datenschutz-Folgenabschaetzung.html)
[Allgemeine Infos IHK München](https://www.ihk-muenchen.de/de/Service/Recht-und-Steuern/Datenschutz/Die-EU-Datenschutz-Grundverordnung/Folgenabsch%C3%A4tzung/)

**Comment by jessvasseur** [comment]
ToDos
* Risikoanalyse
* Abhilfemaßnahmen - Verlinkung auf Code

**Comment by THGthub** [comment]
#50 Enthält die Informationen über Anonymisierung / Pseudonymisierung sowie den Verlauf der Dokumentation über personenbezogene Daten.

**Comment by jessvasseur** [comment]
Finalisierung DSFA
- [ ] Links zum Code / zur entsprechenden ergänzen

**Comment by THGthub** [comment]
DSFA mit den Links auf die Wiki-Seite der Anonymisierung / Pseudonymisierung (History siehe #50) versehen. [Wiki Anonymisierung / Pseudonymisierung](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Anonymisierung-und--Pseudonymisierung)

**Comment by THGthub** [comment]
DSFA final mit der konkreten Auflistung der Umsetzung der Abhilfemaßnahmen erweitert. 
[Praktische Umsetzung der Abhilfemaßnahmen](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenschutz-Folgenabsch%C3%A4tzung#praktische-umsetzung-der-abhilfema%C3%9Fnahmen)
