### ISSUE TITLE
Datenbank mit Colabbook erstellen

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#5]
* Erstellung eines Colabbooks
* Import aller CSV Dateien in eine Datenbank
* SQL Create Statements in separater TXT Datei
* Indexe auf häufig durchsuchten Spalten
* Foreign Key constraints für Verknüpfung der Tabellen

**Comment by THGthub** [comment]
Colabbook zur Erstellung der Tabellen in der Datenbank und zum Füllen der Tabellen mit den synthetischen Daten erstellt. https://github.com/Fuenfgeld/DMA2023TeamA/blob/1a212daa1b7215b331a07480299ffe0a2b41a442/Setup_and_fill_Database.ipynb

**Comment by jessvasseur** [comment]
hab es gerade getestet und funktioniert soweit alles! Welche Spalten einen Index bekommen sollen, können wir ja Montag besprechen. 

Das Notebook sollten wir aber im Ordner [Code](https://github.com/Fuenfgeld/DMA2023TeamA/tree/main/Code) ablegen.

Macht es außerdem Sinn den Pfad im Google SharedDrive und im Skript anzupassen und umbenennen, sodass es zur GitHub Ordnerstruktur passt?
