### ISSUE TITLE
Personenbezogene Daten anonymisieren

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#50]
Ergänzung eines Anonymisierungsschritts im ETL-Prozess um personenbezogene Daten zu entfernen
- Name (anonymisieren)
- Geburtsdatum, Sterbedatum (stattdessen Alter)

**Comment by jessvasseur** [comment]
* Patientenid

**Comment by jessvasseur** [comment]
Geburtsdatum / Sterbedatum -> Alter (auch Alter bei Fall) / weglassen (nicht relevant für Forschungsfrage)
PatientenId -> pseudonymisieren
Name -> weglassen

**Comment by jessvasseur** [comment]
- [x] Anpassung des [Datenbankschemas](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankschema-Datawarehouse)
- [x] Anpassung des [ETL-Skripts](https://github.com/Fuenfgeld/DMA2023TeamA/blob/main/Code/ETL_Process.ipynb)
- [x] Dokumentation in [DSFA](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenschutz-Folgenabsch%C3%A4tzung)

**Comment by THGthub** [comment]
ETL-Skript angepasst. Für Review freigegeben. #65 Pull-Request

**Comment by THGthub** [comment]
Datenbankschema im Verzeichnis [Dokumentation](https://github.com/Fuenfgeld/DMA2023TeamA/tree/main/Dokumentation) aktualisiert. Zusätzlich das Datenbankschema der DWH-Datenbank im [Wiki](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankschema-Datawarehouse) aktualisiert.

**Comment by THGthub** [comment]
DSFA soweit angepasst: [Doku über personenbezogene Informationen](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankschema-Datawarehouse) + [Absatz über Anonymisierung / Pseudonymisierung](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankschema-Datawarehouse) angefertigt und eingefügt. Nur noch die Links auf die Eigenständige Wiki-Page der Anonymisierung / Pseudonymisierung muss noch eingefügt werden.

**Comment by THGthub** [comment]
Reopen, da die Wiki-Page noch fehlt.

**Comment by THGthub** [comment]
[Wiki-Seite zur Anonymisierung und Pseudonymisierung](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Anonymisierung-und--Pseudonymisierung) erstellt, Link auf die Wiki-Seite in der DSFA gesetzt, Grafik erstellt.

**Comment by THGthub** [comment]
File im Ordner [Dokumentation](https://github.com/Fuenfgeld/DMA2023TeamA/blob/main/Dokumentation/Anonymisierung_Pseudonymisierung.png) abgelegt, welches die Anonymisierung und Pseudonymisierung grob beschreibt. Damit kann diese Issue geschlossen werden.
