### ISSUE TITLE
Grafisches Datenbankschema erstellen

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#6]
* Erstellung eines grafischen Datenbankschemas der Datenbank
* Stammdaten und Bewegungsdaten

**Comment by jessvasseur** [comment]
ER Diagramm aus https://github.com/Fuenfgeld/DMA2023TeamA/issues/5 als png speichern und im GitHub Repository ablegen

**Comment by THGthub** [comment]
ER-Diagramm als .png in den Repository-Ordner "Dokumentation" abgelegt: [ER-Diagramm](https://github.com/Fuenfgeld/DMA2023TeamA/blob/c6110537cd20aaa29ec09d4f104c861bd5d9c807/Dokumentation/ER-Diagramm_Datenbankschema.png)

**Comment by THGthub** [comment]
#19 Durch Ergänzung der Tabelle "Medications" (Pull-Request #20) muss auch das grafische Datenbankschema erweitert werden.
Das ER-Diagramm auf der [Datenbankschema-Wikiseite](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankschema) und im Ordner [Dokumentation](https://github.com/Fuenfgeld/DMA2023TeamA/tree/main/Dokumentation) muss angepasst werden.

**Comment by THGthub** [comment]
ER-Diagramm des [ Datenbankschema ](https://github.com/Fuenfgeld/DMA2023TeamA/blob/f11e3062e8dda262ffcdec7c4e8bc53152e9b834/Dokumentation/ER-Diagramm_Datenbankschema_v2.png) im Ordner [Dokumentation](https://github.com/Fuenfgeld/DMA2023TeamA/tree/main/Dokumentation) geupdated. Issue kann wieder geschlossen werden.
