### ISSUE TITLE
Permalinks zu SQL Statements in Wiki überprüfen

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#67]
In den Wiki-Seiten zu den einzelnen Tabellen im[Datenbankschema Quelldatenbank](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankschema) und [Datenbankschema Data Warehouse](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankschema-Datawarehouse) sind Links auf die entsprechenden SQL Statements enthalten. 

Zum Teil verweisen diese auf alte Versionen des entsprechenden Skripts und müssen entsprechend angepasst werden.

**Comment by THGthub** [comment]
Alle Permalinks zu den SQL-Statements in den Wiki-Seiten des [Datenbankschema Quelldatenbank](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankschema) ausgebessert.

**Comment by THGthub** [comment]
Alle Permalinks in den Wiki-Seiteden des [Datenbankschema Data Warehouse](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankschema-Datawarehouse)  ausgebessert.
