### ISSUE TITLE
Geeignete Lizenz für Repository auswählen und verlinken

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#69]
https://docs.github.com/de/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by THGthub** [comment]
Als Lizenz eignet sich nach Sichtung die MIT-Lizenz am besten: [GitHub-Doku MIT License](https://choosealicense.com/licenses/mit/#)

**Comment by THGthub** [comment]
Lizenz für das Repository gewählt und in den Main-Brach gepushed. 
Link zum File: [License](https://github.com/Fuenfgeld/DMA2023TeamA/blob/15af7d6d05c519cdff43dfee6f06454b8d237421/LICENSE).
