### ISSUE TITLE
Dokumentation Datenbank erstellen

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#7]
eine Seite pro Tabelle mit folgenden Informationen
* SQL Create Statement
* Tabelle mit folgenden Spalten
- Spalten Bezeichnung,
- Spalten Datentyp,
- Spalten Inhaltsbeschreibung,
- falls zutreffend Index (Index Name + Index Typ)
- falls zutreffend Foreign Key constraint (Link zu anderer Tabelle)

**Comment by THGthub** [comment]
Tabellenerstellung, inklusive grafischem Datenbankschema im Wiki dokumentiert.
Datenbankerstellung: [Datenbankerstellung_Wiki](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankerstellung)
Grafisches Datenbankschema: [Datenbankschema](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankschema)
Tabelle "Patients": [Patients](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22patients%22)
Tabelle "Payers": [Payers](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22Payers%22)
Tabelle "Encounters": [Encounters](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22Encounters%22)
Tabelle "Procedures": [Procedures](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22Procedures%22)
Tabelle "Conditons": [Conditions](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22Conditions%22)
Tabelle "Payer Conditions": [Payer Transitions](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22Payer-Transitions%22)

**Comment by THGthub** [comment]
Noch fehlend: Im Zuge der Dokumentation über die Quelldaten (Issue: #4) auch Dokumentieren, wie die Daten in die Datenbank geladen wurden. Dazu das Skript [Setup_and_fill_Database](https://github.com/Fuenfgeld/DMA2023TeamA/blob/c6110537cd20aaa29ec09d4f104c861bd5d9c807/Setup_and_fill_Database.ipynb)  noch ausführlich Dokumentieren.

**Comment by jessvasseur** [comment]
ich finde das Skript schon relativ ausführlich dokumentiert und bin nicht sicher, ob hier noch Ergänzungen notwendig sind. 
Die Dokumentation der Quelldaten habe ich jetzt zunächst auf die tatsächlichen Informationen zu den synthetischen Daten beschränkt.

**Comment by THGthub** [comment]
Durch die Erweiterung der Datenbank um die Tabelle "Medications" #19 (Pull-Request #20) muss eine Wiki-Seite zur Tabelle "Medications" erstellt werden.

**Comment by THGthub** [comment]
Dokumentation im Wiki durch @jessvasseur erstellt:  [Tabelle "Medications"](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Tabelle-%22medications%22)

**Comment by THGthub** [comment]
Über #6 geupdatetes, grafisches Datenbankschema im Wiki [Datenbankschema](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankschema) aktualisiert. 
Aufzählung der Tabellen um die Tabelle "medications" Wiki [Datenbankschema](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankschema) ergänzt.

**Comment by THGthub** [comment]
Tabellarische Auflistung der Tabellen und der Rohdaten auf der Wiki-Page [Datenbankerstellung](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenbankerstellung) geupdatet.
