### ISSUE TITLE
Überblick GitHub Repository erstellen

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#71]
Inhalte des GitHub Repositories in Wiki dokumentieren

**Comment by THGthub** [comment]
Page über das [GitHub-Repository](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/%C3%9Cberblick-GitHub-Repository) gefüllt.

**Comment by jessvasseur** [comment]
der Überblick ist nach kleineren Korrekturen und Ergänzungen fertig
