### ISSUE TITLE
Fehler in Wiki-Seiten ausbessern

### ISSUE THREAD

**Issue by THGthub** [Fuenfgeld/DMA2023TeamA#75]
In den Wiki-Seiten auf Fehlersuche gehen und Schreibfehler oder Formatierungsfehler bzw. fehlende Links ausbessern.

**Comment by jessvasseur** [comment]
komplettes Wiki wurde einmal reviewed und einige kleine Korrekturen bzw. Ergänzungen vorgenommen

**Comment by jessvasseur** [comment]
@THGthub @Regfis Bitte bis Donnerstag 02.03.2023 das Wiki nochmal durchgehen, überprüfen und ggf. korrigieren. Dann erfolgt der Release des GitHub Repositories (siehe https://github.com/Fuenfgeld/DMA2023TeamA/issues/70) und die Archivierung des Repositories auf Zenodo (siehe https://github.com/Fuenfgeld/DMA2023TeamA/issues/58) zum Projektabschluss.

**Comment by jessvasseur** [comment]
Wiki wurde finalisiert
