### ISSUE TITLE
Readme finalisieren

### ISSUE THREAD

**Issue by THGthub** [Fuenfgeld/DMA2023TeamA#78]
Follow-Up zu Issue #11 - To-Do:

- [x] Grafik mit Projektprozess updaten (siehe #59)
- [x] Links zur Anonymisierung einfügen
- [x] Reproduzierbarkeits-Abschnitt (Wie ist das Projekt auszuführen) updaten
- [x] Revision

**Comment by jessvasseur** [comment]
Das Readme-File wurde folgendermaßen überarbeitet
* fehlende Abschnitte (Datenanalyse, Archivierung, Anonymisierung/Pseudonymisierung) wurden ergänzt
* Links zu den Notebooks wurden korrigiert
* das aktualisierte Projektschema (siehe https://github.com/Fuenfgeld/DMA2023TeamA/issues/59) wurde verlinkt

**Comment by THGthub** [comment]
Readme finalisiert.
