### ISSUE TITLE
Hilfe: Projekt mit Repository verlinken

### ISSUE THREAD

**Issue by jessvasseur** [Fuenfgeld/DMA2023TeamA#8]
Als Collaborator lassen sich mit dem eigenen Github Account erstellte Projekte nicht mit diesem Repository verlinken. 
Laut [Github Doku](https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/adding-your-project-to-a-repository) muss das Projekt dem Besitzer des Repositories gehören.

**Comment by Fuenfgeld** [comment]
Projekt erstellt

**Comment by jessvasseur** [comment]
Könntest du das erstellte Projekt auch noch mit unserem Repository verlinken? Vielen Dank!

**Comment by Fuenfgeld** [comment]
![image](https://user-images.githubusercontent.com/32547123/212905156-d372cd78-eccf-4d29-979a-d7ad2424eab6.png)
ist schon

**Comment by Fuenfgeld** [comment]
es sollte jetzt funktionieren. @jessvasseur kannst du kurz feedback geben?

**Comment by jessvasseur** [comment]
perfekt - jetzt ist es verlinkt und funktioniert. Vielen Dank!
