### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/DMA2023TeamA#83]
![image](https://user-images.githubusercontent.com/32547123/222379438-6c45ff72-abb9-4b7c-aeaf-4d03283c4e37.png)
Der DMP sollte das start dokument des Projektes sein. In eurem Innhalts verzeichniss wird das nicht klar.
![image](https://user-images.githubusercontent.com/32547123/222379878-5c00cac0-fb68-48ea-a98c-7e1ae4097c6a.png)
- verlinkt eure Grafiken mit dem Code der diese generiert
- 
![image](https://user-images.githubusercontent.com/32547123/222380520-269591ba-eeb1-4f26-ac01-a7585e2fd0aa.png)

bitte fügt den link zu dem Google colabbook ein.

**Comment by jessvasseur** [comment]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/86002179/222386646-ca954e71-ea1b-4f24-8836-e9153aaeb893.png">
Inhaltsverzeichis angepasst - ich hoffe das entspricht so eher den Vorstellungen?

**Comment by jessvasseur** [comment]
Die Bilder unter [Datenqualität](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenqualit%C3%A4t/) wurden auf die entsprechenden Code-Blöcke im Skript (innerhalb der Github Development Umgebung) verlinkt,

@Fuenfgeld ist die Verlinkung so in Ordnung?

**Comment by jessvasseur** [comment]
@Fuenfgeld
> bitte fügt den link zu dem Google colabbook ein.

das heißt wir sollen in die Notebooks selber den Link zu dem jeweiligen Google Colabbook einfügen? Wir verweisen im gesamten Wiki bereits sowohl auf die Notebooks im GitHub Repository als auch auf die entsprechenden Notebooks in der geteilten Google Drive Ablage (Direktlink Google Colab).

**Comment by Fuenfgeld** [comment]
Beim speichern in Github einfach das Häckchen anklicken.
![image](https://user-images.githubusercontent.com/32547123/222400508-4fc5734a-3cf8-4e9b-a72b-674841c3da3c.png)

**Comment by jessvasseur** [comment]
Links wurden entsprechend ergänzt - das Issue wurde dabei automatisch geschlossen und wird wieder geöffnet, falls weiteres Feedback zu erwarten ist

**Comment by Fuenfgeld** [comment]
> Die Bilder unter [Datenqualität](https://github.com/Fuenfgeld/DMA2023TeamA/wiki/Datenqualit%C3%A4t/) wurden auf die entsprechenden Code-Blöcke im Skript (innerhalb der Github Development Umgebung) verlinkt,
> 
> @Fuenfgeld ist die Verlinkung so in Ordnung?

Die Figure benötigen eine description und da gehört das rein.

**Comment by jessvasseur** [comment]
> Die Figure benötigen eine description und da gehört das rein.

![image](https://user-images.githubusercontent.com/86002179/222409700-0354d463-d768-442b-a834-c94a66ce4f8d.png)
erledigt
