### ISSUE TITLE
Breast Cancer Dataset in GitHub laden

### ISSUE THREAD

**Issue by THGthub** [Fuenfgeld/DMA2023TeamA#9]
Die csv-Dateien des Breast Cancer Synthea-Datensets sollten in GitHub geladen werden, damit jeder auf die Files zugreifen und unsere Prozesse nachvollziehen kann. 
csv-Dateien, die im Verlauf des Projektes nicht gebraucht werden, können später über eine eigene Issue entfernt werden.

**Comment by jessvasseur** [comment]
die Frage ist, ob wir das dürfen - Thema Datenschutz? In einem echten Projekt würden die Rohdaten vermutlich personenbezogene Daten enthalten (Name etc.), die man nicht veröffentlichen dürfte. Hier ist das nicht der Fall - es sind zwar personenbezogene Daten drin, aber da es sich nur um synthetische Daten handelt ist es kein Problem.

Trotzdem überlege ich gerade, ob wir die Rohdaten tatsächlich im Repository ablegen sollten oder nur einen Hinweis auf die Quelle in der Dokumentation (die Synthea Daten kann ja prinzipiell jeder direkt dort generieren).
